name = "JsonBlogPost"
version = "0.1.0"
defaultTargets = ["jsonblogpost"]

[[require]]
name = "verso"
scope = "leanprover"
rev = "v4.25.1"

[[require]]
name = "json-schema"
git = "https://github.com/josephmckinsey/json-schema-lean.git"
rev = "f1be1941e1b99941a483e1c507d8a32c7296b674"               # currently main

[[require]]
name = "lean-uri"
git = "https://github.com/josephmckinsey/lean-uri.git"
rev = "v4.24.0-patch1"

[[lean_lib]]
name = "JsonBlogPost"

[[lean_exe]]
name = "jsonblogpost"
root = "Main"
